### ISSUE TITLE
Створення БД (backend)

### ISSUE THREAD

**Issue by AnnaHuskova** [AnnaHuskova/Green-Spaces-Strategy-Development#10]
https://www.youtube.com/watch?v=f1s6Eq4nx0g&t=2s

https://aws.amazon.com/free/?nc1=h_ls&all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all

**Comment by Andygol** [comment]
Для початку використовуємо MongoDB Free plan

**Comment by Andygol** [comment]
RE https://github.com/AnnaHuskova/Green-Spaces-Strategy-Development/issues/13
Репо для бекенду - https://github.com/AnnaHuskova/gssd_back_end

**Comment by Andygol** [comment]
https://blog.andygol.co.ua/uk/2024/06/26/розгортаємо-контейнер-з-приватного-реєстру-ghcr-в-ecs/
