### ISSUE TITLE
Додати в pop up дві кнопочки: "докладна інформація" та "подати звернення"

### ISSUE THREAD

**Issue by Andygol** [AnnaHuskova/Green-Spaces-Strategy-Development#15]
Re: #9

Розширити функціонал Popupʼу двома кнопками

- [ ] Докладна інформація
- [ ] Подати звернення

Ці дві кнопки будуть потім реалізовувати відповідну логіку для полегшення навігації та виконання дій користувачем.

## Докладна інформація 

🚧  to be done

## Подати звернення

🚧 to be done

**Comment by AnnaHuskova** [comment]
Дані та стилі кнопок описані в ticket #41
