### ISSUE TITLE
Додати favicon

### ISSUE THREAD

**Issue by Andygol** [AnnaHuskova/Green-Spaces-Strategy-Development#39]
Було б добре замінити стандартну іконку Реакт на власну іконку

<img width="1110" alt="Monosnap Image 2024-09-16 01-44-07" src="https://github.com/user-attachments/assets/a09403bf-ebee-4913-b4fb-4076bd46b774">

**Comment by AnnaHuskova** [comment]
![Image](https://github.com/user-attachments/assets/6e98ebaa-0408-4049-9f6c-238efe0fbc12)
Замінити на лого проєкту
