### ISSUE TITLE
Редагувати панель фільтрів

### ISSUE THREAD

**Issue by AnnaHuskova** [AnnaHuskova/Green-Spaces-Strategy-Development#44]
1. Змінити логіку роботи:
а) Кожний розділ 
'Статус'
'На утриманні'
'За типом'
має бути представлений окремим реакт компонентом для подальшого під'єднання фільтрів за розділом.
![Image](https://github.com/user-attachments/assets/83abcd4b-9e84-4032-85be-4a0ae886c1f4)

б) При натисканні на іконку розділу розкривається панель із фільтрами що відповідають розділу - реакт компоненту.
Дизайн за посиланням у figma https://www.figma.com/design/NBUwb8UqPGHSwVrefIOFl0/Untitled?node-id=435-178&node-type=frame&t=Rm8eryy064vfXDBn-0

![Image](https://github.com/user-attachments/assets/85285e31-d54d-4415-9914-805c31928adf)

2. Прибрати з панелі фільтри `not supervised` та `supervised`
![Image](https://github.com/user-attachments/assets/0cf57b42-b395-4837-9a8a-a893a362e300)

3. Прибрати з панелі перемикач тайлів мапи та потім перенести його за умовами що описані в ticket #42
![Image](https://github.com/user-attachments/assets/caccea93-e757-43eb-bf45-cf45d3587798)

**Comment by AnnaHuskova** [comment]
Додати до розгорнутої панелі фільтрації елемент - іконку згортання до панелі згорнутої панелі фільтрації із додаванням transition від згорнутої панелі до розгорнутої та навпаки.
іконка ![Image](https://github.com/user-attachments/assets/e1beca3c-9441-4106-866f-e666ee35b5c2)
 у figma https://www.figma.com/design/NBUwb8UqPGHSwVrefIOFl0/Untitled?node-id=435-178&node-type=frame&t=DfVEJ4QfounNzWKJ-0


![Image](https://github.com/user-attachments/assets/d771f3a6-65ed-4aae-bf0d-7f9f11224e58)

**Comment by Andygol** [comment]
closed by PR #57
