### ISSUE TITLE
Перенести вимірювання відстані

### ISSUE THREAD

**Issue by AnnaHuskova** [AnnaHuskova/Green-Spaces-Strategy-Development#47]
Перенести вимірювання відстані на мапі з лівого боку у правий.
Врахувати обмеження аби модальне вікно не перекривало цей елемент, або не ховалось за цей елемент.
![Image](https://github.com/user-attachments/assets/908d697e-0848-4946-ab52-215dad42708c)

**Comment by Andygol** [comment]
done
